version: '3.7'

services:
  web:
    image: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - app
    ports:
      - 8181:80
      - 1234:1234

  app:
    build: .
    volumes:
      - ./app:/app
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - BYEBUG_PORT=1234
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uex
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
