default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: uex
  host: db
  port: 5432
  pool: 5
  
development:
  <<: *default
  database: uex_development

test:
  <<: *default
  database: uex_test

production:
  <<: *default
  database: uex_production